### PR TITLE
GitHub: Changing repo while creating issue clears all fields

### LINKED ISSUE #10542: [Github] Changing repo while creating issue clears all fields
### Extension

https://www.raycast.com/raycast/github

### Description

I would strongly prefer to type the issue title before selecting a repository. This gets the most important information out of my head first, so I don't have to keep it in short-term memory. This makes me much less likely to forget. 

However, if I select a repository after entering the title, the title is cleared.

Thanks a lot for your work!

### Steps To Reproduce

1. Start creating a new github issue
2. Enter title
3. Select repository

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### PR DESCRIPTION
**Pull request by bangerang**
## Description
Create Issue and Create Pull Request now remembers the title when switching repository.
Closes #10542.
## Screencast
CleanShot 2024-03-19 at 18 53 08@2x

CleanShot 2024-03-19 at 18 53 53@2x

## Checklist
- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by xilopaint** [comment]
@bangerang You need to add an entry to `CHANGELOG.md`.

**Comment by antonengelhardt** [comment]
@bangerang I believe you have to put your Raycast username into the `package.json` file and not your GitHub Username.

File: extensions/github/src/create-issue.tsx [hunk 1]
```diff
@@ -123,7 +123,7 @@ export function IssueForm({ draftValues }: IssueFormProps) {
   const milestones = data?.repository?.milestones?.nodes;
 
   useEffect(() => {
-    setValue("title", "");
+    setValue("title", values.title);
```
Comment (thomaslombart) [inline extensions/github/src/create-issue.tsx:126]: Isn't removing the line enough to fix it?

Comment (bangerang) [reply extensions/github/src/create-issue.tsx]: You are right @thomaslombart, this has been fixed

**Comment by thomaslombart** [comment]
I merged something in between @bangerang, so there's a small conflict in the `CHANGELOG.md` 😬

**Comment by bangerang** [comment]
Should be resolved now @thomaslombart

**Review by thomaslombart — APPROVED** [review]
