### PR TITLE
Reuse raycast node interpreter in bitwarden extension

### LINKED ISSUE #510: [Extension Bug] Bitwarden Error
# Extension – [Bitwarden](https://github.com/raycast/extensions/tree/main/extensions/bitwarden)

Author: @pomdtr

## Description

Can't run the Bitwarden extension. I keep getting the **Something went wrong** error upon running it.
image

 Error log pasted below:
```
Error: Command failed with exit code 1: /usr/local/bin/bw status
/usr/local/Cellar/bitwarden-cli/1.20.0/libexec/lib/node_modules/@bitwarden/cli/node_modules/webidl-conversions/lib/index.js:357
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/Cellar/bitwarden-cli/1.20.0/libexec/lib/node_modules/@bitwarden/cli/node_modules/whatwg-url/dist/URL.js:3:21)

/usr/local/Cellar/bitwarden-cli/1.20.0/libexec/lib/node_modules/@bitwarden/cli/node_modules/webidl-conversions/lib/index.js:357
    } catch {
            ^

SyntaxError: Unexpected token {
createScript:vm.js:80:10
Object.runInThisContext:vm.js:139:10
Module._compile:module.js:617:28
Object.Module._extensions..js:module.js:664:10
Module.load:module.js:566:32
tryModuleLoad:module.js:506:12
Function.Module._load:module.js:498:3
Module.require:module.js:597:17
require:module.js:11:18
Object.<anonymous>:URL.js:3:21
Lr:search.js:6:57
search.js:6:10106
processTicksAndRejections:task_queues:96:5
async ke.status:search.js:11:1364
async r:search.js:6:12621
```

## Steps To Reproduce

1. Download Bitwarden extension
2. Install Bitwarden CLI
3. Try running any of the Bitwarden extension commands

## The current behavior
I can't run the extension because of the error posted above.

## The expected behavior
Should be able to run the extension and its commands without any issues.

### Raycast version
Version: 1.26.2

### PR DESCRIPTION
**Pull request by pomdtr**
## Description

Fixes #510

## Type of change

- Bug fix / improvement for my extension

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @pomdtr 👋 

Thanks for the update, for the most of the users it should be just working, I think it's fine for advanced users to have the possibility to change the path.

Could you correct the [spelling error here](https://github.com/raycast/extensions/blob/3767387bf8bb24109bbcbc55c046d309d42455dd/extensions/bitwarden/package.json#L70) before we're merging it 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by pomdtr** [comment]
Done!

**Review by pernielsentikaer — APPROVED** [review]
Thanks, @pomdtr 💪 

I'm going to accept it and then will my colleague do a final review before it's finally merged.

**Comment by mathieudutour** [comment]
Before merging, I'd like to get some context: could we use the node runtime that raycast is installing? You can find it under `~/Library/Application Support/com.raycast.macos/NodeJS/runtime/16.10.0/bin`. You can't easily access this path yet but we could use `process.env.NODE_PATH` for it (we set something to this variable but it's the wrong path, I'll fix it tomorrow)

**Comment by pomdtr** [comment]
I just tried it, it works really well ! This is a much better solution.

**Comment by pernielsentikaer** [comment]
Ah yeah, smart way! Didn't think about that - nice way 💪

File: extensions/bitwarden/src/api.ts [hunk 1]
```diff
@@ -1,23 +1,26 @@
 import { getPreferenceValues } from "@raycast/api";
 import execa from "execa";
 import { existsSync } from "fs";
-import which from "which";
+import { dirname } from "path/posix";
```
Comment (mathieudutour) [inline extensions/bitwarden/src/api.ts:4]: any reason to use `path/posix` instead of just `path`? If we ever want to be multi platform (granted it won't work with home-brew anyway), `path` will work out of the box

**Review by mathieudutour — APPROVED** [review]
