### PR TITLE
Update bitwarden extension: fix search when vault contains SSH keys

### LINKED ISSUE #15837: [Bitwarden Vault] ...
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Raycast Version

1.87.5

### macOS Version

15.2

#### Error:
```
TypeError: Cannot use 'in' operator to search for 'tooltip' in undefined

sA:index.js:17:11365
index.js:17:11022
    at Array.map (<anonymous>)
aA:index.js:17:11015
```

### Steps To Reproduce

open raycast

### Current Behaviour

just open the extension in raycast

### Expected Behaviour

list all passwords

### PR DESCRIPTION
**Pull request by jose-elias-alvarez**
## Description

Closes #15837 and #16976.

Currently, the Search Vault command, the extension's main entry point, errors out if the vault contains an SSH key, a new item type added in late 2024. (This is why some users may not have any problems and also why downgrading to an earlier version of the CLI "fixes" the issue, since older versions just ignore SSH keys.)  

This PR updates the extension's code to correctly handle the new item type. It displays SSH keys in the list of search results and adds an action to copy the public key to the clipboard. (I can also add an action to copy the private key and / or key fingerprint, though I'm not sure how useful these would be.)

I also added a check to ensure that the command won't completely error out if a new item type is added in the future (it'll have placeholder icons and no actions, which seems sensible until proper handling can be added in a PR similar to this one).

Also, while not related, I went ahead and fixed a warning generated by specifying a shortcut for `Action.SubmitForm` (Raycast is already overriding this to Command + Enter).

## Screencast

An SSH key in search results:

CleanShot 2025-03-02 at 12 59 17

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
@jomifepe can you check this?

File: extensions/bitwarden/src/types/vault.ts [hunk 1]
```diff
@@ -88,6 +90,12 @@ export interface Card {
   code: string | null;
 }
 
+export interface SshKey {
+  privateKey: string;
+  publicKey: string;
+  keyFingerprint: string;
+}
```
[the remark this answers is not in the document]
Comment (jose-elias-alvarez) [reply extensions/bitwarden/src/types/vault.ts:97]: Good bot. This is a fair observation, but at least as of now, SSH keys are not directly editable in the Bitwarden GUI (you have to either import them or generate them in Bitwarden itself), so I don't believe these are truly nullable, but I'm happy to change this for consistency.

File: extensions/bitwarden/src/components/RepromptForm.tsx [hunk 2]
```diff
@@ -17,7 +17,7 @@ const RepromptForm = (props: RepromptFormProps) => {
       navigationTitle="Confirmation Required"
       actions={
         <ActionPanel>
-          <Action.SubmitForm title="Confirm" onSubmit={onSubmit} shortcut={{ key: "enter", modifiers: [] }} />
+          <Action.SubmitForm title="Confirm" onSubmit={onSubmit} />
```
Comment (jomifepe) [inline extensions/bitwarden/src/components/RepromptForm.tsx:20]: Thanks for fixing the warnings 🙏

File: extensions/bitwarden/src/components/searchVault/actions/CopyPublicKeyAction.tsx [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+
+  const handleCopyPublicKey = async () => {
+    try {
+      const publicKey = await getUpdatedVaultItem(
+        selectedItem,
+        (item) => item.sshKey?.publicKey,
+        "Getting public key..."
+      );
+      if (publicKey) {
+        await Clipboard.copy(publicKey);
```
Comment (jomifepe) [inline extensions/bitwarden/src/components/searchVault/actions/CopyPublicKeyAction.tsx:22]: We should pass the transient flag depending on the preference here too.

```suggestion
        await Clipboard.copy(publicKey, { transient: getTransientCopyPreference("other") });
```

File: extensions/bitwarden/src/components/searchVault/ItemActionPanel.tsx [hunk 4]
```diff
@@ -73,6 +74,11 @@ const VaultItemActionPanel = () => {
           <ShowNotesAction />
         </ActionPanel.Section>
       )}
+      {type === ItemType.SSH_KEY && (
+        <ActionPanel.Section>
+          <CopyPublicKeyAction />
+        </ActionPanel.Section>
```
Comment (jomifepe) [inline extensions/bitwarden/src/components/searchVault/ItemActionPanel.tsx:80]: 💡 Might be useful to also have copy actions for the private key and fingerprint. Would you mind creating these?

**Review by jomifepe — COMMENTED** [review]
Great addition 💯 
Looks clean overall. I've left a few comments.

**Comment by jose-elias-alvarez** [comment]
Thanks for the feedback @jomifepe, should be good to go now.

File: extensions/bitwarden/src/components/searchVault/ItemActionPanel.tsx [hunk 5]
```diff
@@ -16,10 +16,13 @@ import {
   CopyLoginUrisActions,
   CopyCustomFieldsActions,
   PasteTotpAction,
+  CopyPublicKeyAction,
```
Comment (jomifepe) [inline extensions/bitwarden/src/components/searchVault/ItemActionPanel.tsx:19]: Just needs the exports on in the `index.ts`

```suggestion
  CopyPublicKeyAction,
  CopyKeyFingerprintAction,
  CopyPrivateKeyAction
```

File: extensions/bitwarden/src/types/vault.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (jomifepe) [reply extensions/bitwarden/src/types/vault.ts:97]: Looks good, we can leave it like this and change if necessary.

**Review by jomifepe — APPROVED** [review]
Looks great, good job! Ship it :shipit:

**Comment by pernielsentikaer** [comment]
Can we merge as it is now @jomifepe

**Comment by jomifepe** [comment]
> Can we merge as it is now @jomifepe

I'm not sure if the comment was resolved, it's still not exported [here](https://github.com/raycast/extensions/pull/17492/files#diff-d56996193337602f93564a5b98b463911cd713e20f33b1fc79f09f1d93151ed6R16) and imported [here](https://github.com/raycast/extensions/pull/17492/files#diff-5e1b967ac6b55b17e5f08c5730ce1216d68c63f39cb51d766a4cb55a59cfb30aR19) 👀

But it wasn't a blocker, so feel free to merge anyway!

**Comment by pernielsentikaer** [comment]
Let's do that and have an eye out 🙂

**Review by pernielsentikaer — APPROVED** [review]
Approved 🔥
