### PR TITLE
Jira: Fix missing error title

### LINKED ISSUE #6011: [Jira] Missing `title` on Open Issues command
### Extension

https://www.raycast.com/raycast/jira

#### Error:
```
Error: Rendering failed:
Missing required component property "title"
```

### Steps To Reproduce

1. In Production
2. Logged in as (me)
3. Run "Open Issues" or "Watched Issues" command
4. All good
5. Create an issue via the "Create Issue" command
6. Run "Open Issues" or "Watched Issues" command
7. Receive an error

Screenshot 2023-04-18 at 14 22 08

### Current Behaviour

It seems like the API returns an issue with a missing title? But when I open the Jira list in the browser there are no issues without a title. I can’t debug this unfortunately without knowing which issue it involves.

### Expected Behaviour

This command used to work. I’m expecting to see a list of issues assigned to me or ones I am watching. This used to work until a couple of days ago. It seems to break after running the "Create Issue" command. If the API returns an issue without a `title`, maybe it should be filtered out before trying to render the list.

### PR DESCRIPTION
**Pull request by thomaslombart**
## Description

For some reasons, statuses in Jira may not have categories. Problem is, these categories are used as a section title in various commands such as `Open Issues` causing the error:

```
Error: Rendering failed:
Missing required component property "title"
```

Closes #6011 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

File: extensions/jira/src/components/IssueDetail.tsx [hunk 1]
```diff
@@ -74,7 +74,9 @@ export default function IssueDetail({ initialIssue, issueKey }: IssueDetailProps
             title="Status"
             text={{
               value: issue?.fields.status.name || "",
-              color: getStatusColor(issue?.fields.status.statusCategory.colorName),
+              color: issue.fields.status.statusCategory
```
Comment (mathieudutour) [inline extensions/jira/src/components/IssueDetail.tsx:77]:
```suggestion
              color: issue?.fields.status.statusCategory
```
