### PR TITLE
fix(notion): error when opening page created from form

### LINKED ISSUE #9152: [Notion] Cannot open page after creating it
### Extension

https://www.raycast.com/notion/notion

#### Description
Cannot open page after creating it (Cmd-O throws this error)

#### Error:
```
Error: Minified React error #321

### Steps To Reproduce

1. Install and authorize notion plugin to access at least one db
2. Create a notion page using action "Create database page"
3. After creation, click on "Open Page" or type Cmd-O

### Current Behaviour

Throws the error above

### Expected Behaviour

Open notion app (or browser if app is not installed) in the newly created page.

### PR DESCRIPTION
**Pull request by erics118**
## Description

fixes the error when trying to open a a page that was just created from the `Create Database Page` command

Fix #9152

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

File: extensions/notion/src/components/forms/CreatePageForm.tsx [hunk 1]
```diff
@@ -66,7 +67,7 @@ export function CreatePageForm({ mutate, defaults }: CreatePageFormProps) {
             primaryAction: {
               title: "Open Page",
               shortcut: { modifiers: ["cmd"], key: "o" },
-              onAction: () => handleOnOpenPage(page, useRecentPages().setRecentPage),
+              onAction: () => handleOnOpenPage(page, setRecentPage),
```
Comment (erics118) [inline extensions/notion/src/components/forms/CreatePageForm.tsx:70]: The original error was that it broke the Rule of Hooks. Originally, `useRecentPages` (a hook) was called inside a function. Fix was just to call `useRecentPages` inside the component

**Review by thomaslombart — APPROVED** [review]
🚀
