### PR TITLE
Reflect renamed github repositories

### LINKED ISSUE #9695: [GitHub] Repository name not updated after being renamed on GitHub.com
### Extension

https://www.raycast.com/raycast/github

### Description

When a repository is renamed on GitHub, the updated name is not reflected in Raycast.

### Steps To Reproduce

1. Browse a repository via RayCast -> Search Repositories
2. Rename repository on GitHub
3. Name is not updated in Visited Repositories in Search Repositories

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### PR DESCRIPTION
**Pull request by nesl247**
## Description

Fix #9695 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by nesl247** [comment]
I'm not sure I submitted this PR correctly, given it doesn't follow the standard way to submit a PR (I followed https://developers.raycast.com/basics/contribute-to-an-extension). Let me know if I need to do anything else.

**Comment by pernielsentikaer** [comment]
Hi @nesl247 👋 

It looks correct to me, but you're missing an entry in the `CHANGELOG.md` file.

Here's our guidelines about that: [Version History](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history).

**Comment by nesl247** [comment]
@pernielsentikaer done. The documentation around contributing is a bit confusing. That page seems pretty clear to be about new extensions, not contributing to an existing one, and the changelog entry isn't mentioned in the contributing page at all.

File: extensions/github/src/search-repositories.tsx [hunk 1]
```diff
@@ -45,6 +45,14 @@ function SearchRepositories() {
     { keepPreviousData: true },
   );
 
+  useEffect(() => {
+    if (isLoading) {
+      return;
+    }
+
+    history.forEach((repository) => data?.find((r) => r.id === repository.id && visitRepository(r)));
+  }, [data, isLoading]);
```
Comment (thomaslombart) [inline extensions/github/src/search-repositories.tsx:54]: How is `isLoading` useful to the hook?

```suggestion
  useEffect(() => {
    history.forEach((repository) => data?.find((r) => r.id === repository.id && visitRepository(r)));
  }, [data]);
```

File: extensions/github/src/search-repositories.tsx [hunk 2]
```diff
@@ -45,6 +45,14 @@ function SearchRepositories() {
     { keepPreviousData: true },
   );
 
+  useEffect(() => {
```
Comment (thomaslombart) [inline extensions/github/src/search-repositories.tsx:48]: We could use a comment above the code to explain why this piece of code is useful. It may not be obvious at first.

Comment (nesl247) [reply extensions/github/src/search-repositories.tsx:49]: Added.

**Review by thomaslombart — APPROVED** [review]
