### PR TITLE
[Forked Extensions] Improve error handlers and toasts

### LINKED ISSUE #21220: [Forked Extensions] Issue loading command when repo fork doesn't exist on GitHub account
### Extension

https://www.raycast.com/litomore/forked-extensions

### Raycast Version

v0.29.0.0 (Win Beta)

### macOS Version

Windows 11 24H2 (Build 26100.4946)

### Description

When trying to open the "Manage Forked Extensions" command, I got an unhandled 404 when I didn't have a fork of raycast/extensions. Once I forked the repo properly it works completely fine. 

I managed to figure out where I went wrong, but it might be worth handling this to make it clearer that the GH account needs a fork. It might be more obvious on macOS where Raycast has the full extension functionality & the vanilla fork command, but I was shooting in the dark trying to get it to work on Windows.

```json
{
    "_isRayError": true,
    "code": 2,
    "title": "Unhandled Extension Rejection",
    "name": "HTTPError",
    "message": "Response code 404 (Not Found)",
    "stack": [
        {
            "raw": "    at t.<anonymous> (C:\\Users\\anon\\.config\\raycast-x\\extensions\\264a0901-cc7b-4562-81b3-8a417dd49142\\manage-forked-extensions.js:17:46015)",
            "file": "C:\\Users\\anon\\.config\\raycast-x\\extensions\\node_modules\\got\\dist\\source\\as-promise\\index.js",
            "fileContent": "import { EventEmitter } from 'node:events';\nimport is from '@sindresorhus/is';\nimport PCancelable from 'p-cancelable';\nimport { HTTPError, RetryError, } from '../core/errors.js';\nimport Request from '../core/index.js';\nimport { parseBody, isResponseOk, ParseError, } from '../core/response.js';\nimport proxyEvents from '../core/utils/proxy-events.js';\nimport { CancelError } from './types.js';\nconst proxiedRequestEvents = [\n    'request',\n    'response',\n    'redirect',\n    'uploadProgress',\n    'downloadProgress',\n];\nexport default function asPromise(firstRequest) {\n    let globalRequest;\n    let globalResponse;\n    let normalizedOptions;\n    const emitter = new EventEmitter();\n    const promise = new PCancelable((resolve, reject, onCancel) => {\n        onCancel(() => {\n            globalRequest.destroy();\n        });\n        onCancel.shouldReject = false;\n        onCancel(() => {\n            reject(new CancelError(globalRequest));\n        });\n        const makeRequest = (retryCount) => {\n            // Errors when a new request is made after the promise settles.\n            // Used to detect a race condition.\n            // See https://github.com/sindresorhus/got/issues/1489\n            onCancel(() => { });\n            const request = firstRequest ?? new Request(undefined, undefined, normalizedOptions);\n            request.retryCount = retryCount;\n            request._noPipe = true;\n            globalRequest = request;\n            request.once('response', async (response) => {\n                // Parse body\n                const contentEncoding = (response.headers['content-encoding'] ?? '').toLowerCase();\n                const isCompressed = contentEncoding === 'gzip' || contentEncoding === 'deflate' || contentEncoding === 'br';\n                const { options } = request;\n                if (isCompressed && !options.decompress) {\n                    response.body = response.rawBody;\n                }\n                else {\n                    try {\n                        response.body = parseBody(response, options.responseType, options.parseJson, options.encoding);\n                    }\n                    catch (error) {\n                        // Fall back to `utf8`\n                        try {\n                            response.body = response.rawBody.toString();\n                        }\n                        catch (error) {\n                            request._beforeError(new ParseError(error, response));\n                            return;\n                        }\n                        if (isResponseOk(response)) {\n                            request._beforeError(error);\n                            return;\n                        }\n                    }\n                }\n                try {\n                    const hooks = options.hooks.afterResponse;\n                    for (const [index, hook] of hooks.entries()) {\n                        // @ts-expect-error TS doesn't notice that CancelableRequest is a Promise\n                        // eslint-disable-next-line no-await-in-loop\n                        response = await hook(response, async (updatedOptions) => {\n                            options.merge(updatedOptions);\n                            options.prefixUrl = '';\n                            if (updatedOptions.url) {\n                                options.url = updatedOptions.url;\n                            }\n                            // Remove any further hooks for that request, because we'll call them anyway.\n                            // The loop continues. We don't want duplicates (asPromise recursion).\n                            options.hooks.afterResponse = options.hooks.afterResponse.slice(0, index);\n                            throw new RetryError(request);\n                        });\n                        if (!(is.object(response) && is.number(response.statusCode) && !is.nullOrUndefined(response.body))) {\n                            throw new TypeError('The `afterResponse` hook returned an invalid value');\n                        }\n                    }\n                }\n                catch (error) {\n                    request._beforeError(error);\n                    return;\n                }\n                globalResponse = response;\n                if (!isResponseOk(response)) {\n                    request._beforeError(new HTTPError(response));\n                    return;\n                }\n                request.destroy();\n                resolve(request.options.resolveBodyOnly ? response.body : response);\n            });\n            const onError = (error) => {\n                if (promise.isCanceled) {\n                    return;\n                }\n                const { options } = request;\n                if (error instanceof HTTPError && !options.throwHttpErrors) {\n                    const { response } = error;\n                    request.destroy();\n                    resolve(request.options.resolveBodyOnly ? response.body : response);\n                    return;\n                }\n                reject(error);\n            };\n            request.once('error', onError);\n            const previousBody = request.options?.body;\n            request.once('retry', (newRetryCount, error) => {\n                firstRequest = undefined;\n                const newBody = request.options.body;\n                if (previousBody === newBody && is.nodeStream(newBody)) {\n                    error.message = 'Cannot retry with consumed body stream';\n                    onError(error);\n                    return;\n                }\n                // This is needed! We need to reuse `request.options` because they can get modified!\n                // For example, by calling `promise.json()`.\n                normalizedOptions = request.options;\n                makeRequest(newRetryCount);\n            });\n            proxyEvents(request, emitter, proxiedRequestEvents);\n            if (is.undefined(firstRequest)) {\n                void request.flush();\n            }\n        };\n        makeRequest(0);\n    });\n    promise.on = (event, function_) => {\n        emitter.on(event, function_);\n        return promise;\n    };\n    promise.off = (event, function_) => {\n        emitter.off(event, function_);\n        return promise;\n    };\n    const shortcut = (responseType) => {\n        const newPromise = (async () => {\n            // Wait until downloading has ended\n            await promise;\n            const { options } = globalResponse.request;\n            return parseBody(globalResponse, responseType, options.parseJson, options.encoding);\n        })();\n        // eslint-disable-next-line @typescript-eslint/no-floating-promises\n        Object.defineProperties(newPromise, Object.getOwnPropertyDescriptors(promise));\n        return newPromise;\n    };\n    promise.json = () => {\n        if (globalRequest.options) {\n            const { headers } = globalRequest.options;\n            if (!globalRequest.writableFinished && !('accept' in headers)) {\n                headers.accept = 'application/json';\n            }\n        }\n        return shortcut('json');\n    };\n    promise.buffer = () => shortcut('buffer');\n    promise.text = () => shortcut('text');\n    return promise;\n}\n",
            "line": 92,
            "column": 41,
            "function": "t.<anonymous>"
        },
        {
            "raw": "    at Object.onceWrapper (node:events:633:26)",
            "file": "node:events",
            "line": 633,
            "column": 26,
            "function": "Object.onceWrapper"
        },
        {
            "raw": "    at t.emit (node:events:530:35)",
            "file": "node:events",
            "line": 530,
            "column": 35,
            "function": "t.emit"
        },
        {
            "raw": "    at t._onResponseBase (C:\\Users\\anon\\.config\\raycast-x\\extensions\\264a0901-cc7b-4562-81b3-8a417dd49142\\manage-forked-extensions.js:17:40268)",
            "file": "C:/Users/anon/.config/raycast-x/extensions/264a0901-cc7b-4562-81b3-8a417dd49142/manage-forked-extensions.js",
            "line": 17,
            "column": 40268,
            "function": "t._onResponseBase"
        }
    ],
    "breadcrumbs": [
        {
            "level": "error",
            "category": "Proxy",
            "message": "Proxy configuration error",
            "data": {
                "error": "TypeError: Cannot read properties of null (reading 'indexOf')"
            },
            "timestamp": "2025-08-28T12:26:07.076Z"
        }
    ],
    "diagnostics": {
        "id": "1d5a2019-1b2e-4273-a79c-2216a179a672",
        "extensionName": "forked-extensions",
        "name": "manage-forked-extensions",
        "mode": "view",
        "isDevelopment": false,
        "launchType": "userInitiated",
        "eventLoopUtilization": {
            "idle": 0,
            "active": 0,
            "utilization": 0
        },
        "startedAt": 1756383966652
    },
    "sessionId": "1d5a2019-1b2e-4273-a79c-2216a179a672"
}

``` 

### Steps To Reproduce

1. Install the extension
2. Login to a GitHub account that does not have a fork of raycast/extensions
3. Open "Manage Forked Extensions"

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### PR DESCRIPTION
**Pull request by LitoMore**
## Description

Resolved #21220

- Improve error handling by creating a "catchError" utility function to avoid running rest of the code when an error occurs
- Use a workaround to fix the issue that the "Toast" instance cannot set the "primaryAction.onAction" for some unknown reason
- Fix a wording issue in the "Sync Fork" action title
- Cleanup the redundant "openExtensionPreferences" when Git not found
- Add a new "Diagnostics" action to help users diagnose common issues
- Fix "Sync Anyway" action not working when forking an extension
- Replace all code backticks with double quotes due to Raycast store page cannot display it in good visual
- Bump all dependencies to the latest

~~BTW, I'm not sure why the action workflow treated this PR as a https://github.com/raycast/extensions/labels/new%20extension 🤔~~\
I've created a PR for fixing the wrong label issue: https://github.com/raycast/extensions/pull/21250.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used in the `README` are located outside the metadata folder if they were not generated with our [metadata tool](https://developers.raycast.com/basics/prepare-an-extension-for-store#how-to-use-it)

### CODE REVIEW

File: extensions/forked-extensions/src/operation.ts [hunk 1]
```diff
@@ -134,13 +133,16 @@ class Operation {
...
+    return this.showToast(
+      {
+        title,
+        message,
+        style: options?.style ?? Toast.Style.Failure,
+        primaryAction: options?.primaryAction ?? copyLogsAction,
+        secondaryAction: options?.primaryAction ? copyLogsAction : undefined,
+      },
+      true, // Create a new toast instance to ensure the `primaryAction.onAction` works as expected.
+    );
```
Comment (LitoMore) [inline extensions/forked-extensions/src/operation.ts:138]: The toast-related bug is weird. I cannot use `primaryAction.onAction` on an existing toast. So I added a workaround to spawn a new toast instance for the `showFailureToast` method.

If you are interested in the bug, you can remove the boolean value `true` from the `showToast` method and observe the issue.

The reproduce steps would be:

1. Go to `src/git.ts`, replace the `rev-parse` with`bug-rev-parse` to let the method throw an exception
2. Run the dev mode and open the extension, it will prompt an error
3. Open the error toast and press enter to run the `Copy Logs` action
4. You will notice that nothing happens; the clipboard copies nothing

It's fine if you don't have time to try this bug. I will take a deeper look at this problem later.
