### PR TITLE
GitHub: Accept Repo invite through notification

### LINKED ISSUE #11249: [GitHub] Repo Invite notification results in API error
### Extension

https://www.raycast.com/raycast/github

### Description

When i receive an invitation to a repository, and click the notification, an error is shown

### Steps To Reproduce

1. Have someone invite you to a private repo
2. Wait for the notification
3. Click the notification

Screenshot-CleanShot-006144@2x

### Current Behaviour

An API error is shown

Screenshot-Arc-006146@2x

### Expected Behaviour

The same behavior as if i had clicked the button in the email notifying me about the invite.

### PR DESCRIPTION
**Pull request by antonengelhardt**
## Description

When receiving a Repo invite, the open in browser failed as described in #11249. So this change, checks the reason type of the notification and opens the invitation page for the repo instead.

Closes #11249 

## Screencast

https://github.com/raycast/extensions/assets/106314688/82658b23-1c10-4e06-86a5-773970244235

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by antonengelhardt** [comment]
Feature idea: Instead of opening the invite in the browser, the default Action could be to accept the invite via [the API](https://docs.github.com/en/rest/collaborators/invitations?apiVersion=2022-11-28#accept-a-repository-invitation) and then open the repo.

File: extensions/github/src/unread-notifications.tsx [hunk 1]
```diff
@@ -53,8 +53,12 @@ function UnreadNotifications() {
...
     try {
       const openAndMarkNotificationAsRead = async () => {
-        await open(getGitHubURL(notification, viewer?.id));
-        await octokit.rest.activity.markThreadAsRead({ thread_id: parseInt(notification.id) });
+        if (notification.subject.type === "RepositoryInvitation") {
+          open(`${notification.repository.html_url}/invitations`);
+        } else {
+          await open(getGitHubURL(notification, viewer?.id));
+          await octokit.rest.activity.markThreadAsRead({ thread_id: parseInt(notification.id) });
+        }
```
Comment (antonengelhardt) [inline extensions/github/src/unread-notifications.tsx:61]: We can do the same here as in the raycast dropdown menu (accepting the invite via the API & open the repo home page). Up to you :)

**Review by thomaslombart — APPROVED** [review]
Awesome work! 🚀
