### PR TITLE
[Update Extension] System Monitor: Fix CPU usage

### LINKED ISSUE #7198: [System Monitor] ...
### Extension

https://www.raycast.com/hossammourad/raycast-system-monitor

### Description

Everytime you open the extension the task PMSET spikes multiple times to 100%

the moment you close the extension through raycast it falls to within normal boundaries.

### Steps To Reproduce

open the extensions
See PMSET jump to 100% multipletimes
CleanShot 2023-06-20 at 14 46 26@2x

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### PR DESCRIPTION
**Pull request by lucasmezencio**
## Description

This PR fixes the 100% CPU usage by reducing the frequency of the `PMSET` and the `TOP` calls.

It closes #7198.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

File: extensions/system-monitor/src/Memory/MemoryMonitor.tsx [hunk 1]
```diff
@@ -19,36 +19,66 @@ export default function MemoryMonitor() {
...
+              setError(err);
             });
-          })
-          .catch((error: ExecError) => {
-            setError(error);
-          });
+        }
+      })
+      .then(() => {
+        setIsLoading(false);
```
Comment (mathieudutour) [inline extensions/system-monitor/src/Memory/MemoryMonitor.tsx:61]: I don't think your `setIsLoading(false);` is called at the right time because you aren't waiting for the promises.

You probably need
```diff
getFreeDiskSpace()
      .then((newFreeDisk) => {
-        getMemoryUsage()
+        return getMemoryUsage()
...
```

**Comment by mil3na** [comment]
Hi! Thank you so much for your contribution to Raycast!
My name is Milena and I will be reviewing your extension update today :)

I did not experience my laptop hanging after opening the extension, but I do see the `pmset` process spiking. Using the new version of your extension does not fix this issue.

CleanShot 2023-07-18 at 14 21 37@2x

**Comment by lucasmezencio** [comment]
Hey @mil3na! Thanks for your review. In fact, the spike in the CPU will always happen at the beginning, then, it will spike again in a few seconds, however, before the update, it was constantly high.

Not sure if my fix is the best fix for this issue, but I'm open for suggestions. :)

**Comment by mil3na** [comment]
Aha! Now I see the issue and the fix. Okay, looks good to me :)
