### PR TITLE
[Skills] Fix node homebrew versioned formula resolution

### LINKED ISSUE #27297: [Skills] node: No such file or directory
### Extension

https://raycast.com/keito4/skills

### Raycast Version

Version 1.104.12

### OS Version

macOS Tahoe 26.4

#### Error:
```
Error: Command failed: 'npx' '-y' 'skills@latest' 'list' '-g' '--json'
env: node: No such file or directory

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at ChildProcess.exithandler (node:child_process:414:12)
    at ChildProcess.emit (node:events:518:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:351:12)
```

Image

### Steps To Reproduce

Manage Skills

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### PR DESCRIPTION
**Pull request by raulgg**
## Description

Fixes #27297

Fix two related `skills` extension issues around local Node.js path resolution.

- Add support for versioned Homebrew Node formula paths such as `/opt/homebrew/opt/node@24/bin` when building the CLI `PATH`. This fixes cases where Raycast can find Homebrew `npx` but not the matching `node` binary.
- Validate the optional `Custom npx Path` before spawning the CLI and show a clearer error when the configured path is incorrect, instead of surfacing a misleading downstream command failure.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used in the `README` are located outside the metadata folder if they were not generated with our [metadata tool](https://developers.raycast.com/basics/prepare-an-extension-for-store#how-to-use-it)

### CODE REVIEW

**Comment by DaleSeo** [comment]
Thanks for stepping in to fix the issue, @raulgg. Since the PR is in draft, I'll take a look when it's ready for review.

**Comment by raulgg** [comment]
> Thanks for stepping in to fix the issue, @raulgg. Since the PR is in draft, I'll take a look when it's ready for review.

Thank you, @DaleSeo! I was verifying different scenarios. I hope these changes will resolve the issue reported by the user. I would appreciate your comments on the fix.

File: extensions/skills/src/utils/skills-cli.ts [hunk 1]
```diff
@@ -61,6 +79,37 @@ function normalizeCliError(error: unknown, npxCommand: string): Error {
...
+    if (fileStats.isDirectory()) {
+      throw new InvalidCustomNpxPathError(invalidPathMessage);
+    }
+  } catch (error) {
+    if (error instanceof InvalidCustomNpxPathError) {
+      throw error;
+    }
+
+    throw new InvalidCustomNpxPathError(invalidPathMessage);
+  }
```
Comment (DaleSeo) [inline extensions/skills/src/utils/skills-cli.ts:124]: How about we simplify this?

```suggestion
  let fileStats;
  try {
    fileStats = await stat(customNpxPath);
  } catch {
    throw new InvalidCustomNpxPathError(invalidPathMessage);
  }
  if (fileStats.isDirectory()) {
    throw new InvalidCustomNpxPathError(invalidPathMessage);
  }
```

File: extensions/skills/src/utils/node-path-resolver.ts [hunk 2]
```diff
@@ -107,21 +142,28 @@ export const resolveVersionManagerPaths = async (): Promise<string[]> => {
...
   const systemPaths = ["/usr/bin", "/bin"];
 
   if (process.env.HOME) {
     systemPaths.push(`${process.env.HOME}/.npm/bin`, `${process.env.HOME}/.yarn/bin`);
   }
 
-  const allPaths = [...platformPaths, ...versionManagerPaths, ...systemPaths, process.env.PATH || ""];
+  const allPaths = [
+    ...homebrewPaths,
+    ...homebrewVersionedNodePaths,
```
Comment (DaleSeo) [inline extensions/skills/src/utils/node-path-resolver.ts]: Worth considering whether versioned paths should come before the default bin so explicit version choices win.

File: extensions/skills/src/utils/skills-cli.ts [hunk 3]
```diff
@@ -25,14 +26,31 @@ export function isNpxResolutionError(error: unknown): boolean {
...
 function buildSkillsCliCommand(npxCommand: string, args: string[]): string {
   return [npxCommand, "-y", "skills@latest", ...args].map(shellEscape).join(" ");
 }
 
 async function runSkillsCli(args: string[]): Promise<string> {
-  const npxCommand = getCustomNpxPath() ?? "npx";
+  const customNpxPath = getCustomNpxPath();
+  if (customNpxPath) {
+    await validateCustomNpxPath(customNpxPath);
+  }
```
Comment (DaleSeo) [inline extensions/skills/src/utils/skills-cli.ts:51]: Every call to `runSkillsCli` issues fresh syscalls for the same custom path. Since the preference value is captured at module load via `getPreferenceValues<Preferences>()`, the result won't change mid-session. A tiny memoization similar to `cachedPaths` could be helpful.

**Review by DaleSeo — APPROVED** [review]
Thanks for tackling this, @raulgg! I only have non-blocking suggestions!

**Review by pernielsentikaer — COMMENTED** [review]
@raulgg do you want to have a look at this before we merge it?

File: extensions/skills/src/utils/skills-cli.ts (hunk 1 above)
Comment (raulgg) [reply extensions/skills/src/utils/skills-cli.ts:124]: Good suggestion! I applied this. Thank you!

File: extensions/skills/src/utils/skills-cli.ts (hunk 3 above)
Comment (raulgg) [reply extensions/skills/src/utils/skills-cli.ts:51]: You are correct! I have implemented a simple memoization for the custom path validation as suggested.

File: extensions/skills/src/utils/node-path-resolver.ts (hunk 2 above)
Comment (raulgg) [reply extensions/skills/src/utils/node-path-resolver.ts]: Yes, this is a good point. I'm also considering that we should prefer the `versionManagerPaths` over homebrew ones, as usually those would be initialized in the shell and have precedence over the versions installed through homebrew. I pushed the change for this. Thank you for raising this concern and making me reconsider my initial choice.

**Comment by raulgg** [comment]
> @raulgg do you want to have a look at this before we merge it?

Sure! The feedback is addressed now.

**Review by pernielsentikaer — APPROVED** [review]
Looks good to me, approved 🔥
