### PR TITLE
Brew stream json

### LINKED ISSUE #3502: [Brew] Failed to search on brew Extension
# Extension – [Brew](https://github.com/raycast/extensions/tree/b6892d67347d19c9b07f4116ec21b330e45258ad/extensions/brew/)
Author: @nhojb

## The current behavior
I have an error sending me to try search again and again

## The expected behavior
list all the brew itens 

### Raycast version
Version: 1.43.2

### PR DESCRIPTION
**Pull request by nhojb**
## Description

Reduce memory footprint of the "Search" command by streaming the JSON response data.

Should really fix #3502

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

File: extensions/brew/src/utils.ts [hunk 1]
```diff
@@ -1,15 +1,20 @@
 import { Clipboard, environment, Toast } from "@raycast/api";
 import path from "path";
-import { mkdirSync } from "fs";
-import { stat, readFile, writeFile } from "fs/promises";
+import fs from "fs";
+import { stat } from "fs/promises";
 import fetch, { FetchError } from "node-fetch";
+import { chain } from "stream-chain";
```
Comment (mathieudutour) [inline extensions/brew/src/utils.ts:6]: I'm assuming `stream-chain` is a dependency of `stream-json`? In any case, I would add it as a direct dependency

**Review by mathieudutour — APPROVED** [review]
looks good to me!

I'm wondering if using the algolia index that's used when you search on https://formulae.brew.sh would be a nicer UX 🤔

File: extensions/brew/src/utils.ts (hunk 1 above)
Comment (nhojb) [reply extensions/brew/src/utils.ts:6]: Yes, that's correct. Will add it 👍
