### PR TITLE
fix(notion): date with time

### LINKED ISSUE #10687: Notion: LKe} has an invalid date. If time zone is explicitly provided, start and end must contain date and time
### Extension

https://www.raycast.com/notion/notion

### Description

Hi,
by trying to create an event in my notion calendar I get this error when i specify the time.
image
If I just put the day without time it works.

I'm attaching the log file I generated with this command while trying to reproduce the error, hopefully it will be usefull.
[ray.20240210_144952.log](https://github.com/raycast/extensions/files/14229519/ray.20240210_144952.log)

thank you in advance.

### Steps To Reproduce

Macbook M1 pro
MacOS Sonoma 14.1.1
cmd + space -> create database page -> select my own calendar -> typing "in five minutes" in the date textbox -> selecting the suggestion -> fill in other fields -> cmd + enter

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### PR DESCRIPTION
**Pull request by erics118**
## Description

fix #10687

Fixed bug that prevented creating pages with time
Fixed issue that resulted in an error always being shown when a recent page was deleted or permission was revoked

## Screencast

https://github.com/raycast/extensions/assets/52634785/121666e8-5c56-49b7-8e60-79e6f32eb0af

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

File: extensions/notion/src/utils/notion/database/property.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ export function formatDatabaseProperty(...[type, value]: FormatDatabasePropertyP
     case "date": {
       if (!value) return;
       type DatePropertyTimeZone = Exclude<Extract<PageProperty, { type?: "date" }>["date"], null>["time_zone"];
-      const time = subMinutes(new Date(value), new Date().getTimezoneOffset()).toISOString().split("T")[0];
+      const time = subMinutes(new Date(value), new Date().getTimezoneOffset()).toISOString();
```
Comment (thomaslombart) [inline extensions/notion/src/utils/notion/database/property.ts:22]: This looks a bit weird to me. Why was `.split("T")[0]` used before? Are we sure we're not adding another regression with this fix?

**Review by thomaslombart — APPROVED** [review]
