### PR TITLE
Harvest

### LINKED ISSUE #538: [Extension Bug] Harvest - @eluce2
# Extension – [Harvest](https://github.com/raycast/extensions/tree/main/extensions/harvest)

Author: @eluce2 

## Description
I think this is a bug because it is not showing the project name but empty brackets 

## Steps To Reproduce

1. Add Access Token
2. Account ID 
3. New Time Entry

image

## The current behavior
No Project Name 

## The expected behavior
Show project name

### Raycast version
Version: 1.26.3

### PR DESCRIPTION
**Pull request by eluce2**
## Description

- Fix: Update SWR package to 1.1.2 (handles window.requestAnimationFrame bug)
- Fix: Harvest admins are now limited to only view their own time entries, even if their API creds allow them to view/edit other user's timers in their company.
- New: Support for viewing timers on other days (see below)
- New: Add user preference to control how time entries are sorted
- Improvement: Remove brackets in project picker if no code is present (fixes #538)
- Improvement: Project picker now groups projects by client (more similar the Harvest app)
- Improvement: Now uses new alert dialog for deleting time entry confirmation
- Improvement: Total hours for a given day are shown in the header of the list of time entries

**NOTE:** The new feature that allows editing entries on other days is incomplete, but until there is a Date only form field component, I can't get it to function correctly. Expected behavior is that you would navigate to a different day, then choose the "New Timer" action and the date field would be prefilled to the day that you had navigated to. Due to timezone differences, if I put any date in as the default value, it displays as 6 pm on the previous day. To me, this behavior is worse than not pre-setting the date at all, so I've disabled that part of the feature for now. However, if the date field is left blank, the API will still create the time entry on the correct date this is just not made clear to the user in the form.

Also, please note it was an intentional decision to change the navigation header when switching days, as otherwise there would be no indication of which is your current day if there are no time entires on that day.

## Type of change

Bug fix / improvement for my extension

## Screencast

https://cln.sh/meou3X

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

### CODE REVIEW

**Review by unnamedd — CHANGES_REQUESTED** [review]
Hey @eluce2, would you please do not modify other extensions? 
I saw you are making changes on my Script Commands Store extension and also in the Two Factor Authentication as well. 

Please, rollback those changes.

Tip: _when you develop you extension, open on VSCode only the folder of your extension, if you open the extensions root folder and apply a formatter, it might make unwanted changes on other files._

**Comment by eluce2** [comment]
@unnamedd Sorry about that, this new commit should only effect my own extension. Thanks for the tip, I'll be sure to use that in my future development!

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @eluce2 👋 

It sounds like some nice additions to the extension 💪 

- In the README `recognize` is spelled wrong 😄 
- There is no gracefully handling when token are wrong, can you also add this?

HB7KoBFawfV0f1k7

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
hi @eluce2 👋 

Did you push it correct? It seems like I'm still facing the same hard error 😄 

IgFuJiUwMmAyMGwJ

**Comment by eluce2** [comment]
@pernielsentikaer So that looks like a different error than "invalid API token". At first, I was unable to replicate, but that's because I've been testing with the node production environment. Could this be something polyfilled by the Raycast Dev API, or do I need to adjust my code? Again, you won't get that error when it's running in production.

**Comment by pernielsentikaer** [comment]
Hi @eluce2 👋 

Just to be sure once more, sorry, If I get the extension from Store right now, this is the error you have fixes, yes? (The one with wrong credentials)

4WfWGmgTIAzNySEh

**Comment by eluce2** [comment]
Yes, I'm trapping for the 401 HTTP response now in the latest push, and showing a generic error for any other non-success HTTP statuses

**Review by pernielsentikaer — APPROVED** [review]
hi @eluce2 👋 

Thanks for the update. I'm going to accept it and then will my colleague do a final review before it's finally merged 😄

File: extensions/harvest/src/listTimeEntries.tsx [hunk 1]
```diff
@@ -23,68 +26,291 @@ import {
...
+        if (error.response?.status === 401) {
+          await showToast(
+            ToastStyle.Failure,
+            "Invalid Token",
+            "Your API token or Account ID is invalid. Go to Raycast Preferences to update it."
+          );
+        }
+      } else {
+        await showToast(ToastStyle.Failure, "Unknown Error", "Could not fetch time entries");
+      }
```
Comment (mathieudutour) [inline extensions/harvest/src/listTimeEntries.tsx:83]: Shouldn't it be
```suggestion
      if (error.isAxiosError) {
        if (error.response?.status === 401) {
          await showToast(
            ToastStyle.Failure,
            "Invalid Token",
            "Your API token or Account ID is invalid. Go to Raycast Preferences to update it."
          );
        } else {
          await showToast(ToastStyle.Failure, "Unknown Error", "Could not fetch time entries");
        }
      } else {
        await showToast(ToastStyle.Failure, "Unknown Error", "Could not fetch time entries");
      }
```
so that a 500 or whatever also shows a toast? We might want to show the error message as well (if any, I'm not familiar with the API)

File: extensions/harvest/src/listTimeEntries.tsx [hunk 2]
```diff
@@ -134,36 +364,26 @@ function DeleteEntryAction({
...
+          icon: Icon.Trash,
+          primaryAction: {
+            title: "Delete",
+            style: AlertActionStyle.Destructive,
+            onAction: async () => {
+              await deleteTimeEntry(entry);
+              await onComplete();
+            },
+          },
+        });
```
Comment (mathieudutour) [inline extensions/harvest/src/listTimeEntries.tsx:382]: while you can register a handler for an action, it's more elegant to use the `if (await confirmAlert(...)) { ... }` pattern
```suggestion
        if (await confirmAlert({
          title: "Delete Time Entry",
          message: "Are you sure? This cannot be undone",
          icon: Icon.Trash,
          primaryAction: {
            title: "Delete",
            style: AlertActionStyle.Destructive,
          },
        })) {
          await deleteTimeEntry(entry);
          await onComplete();
        }
```

I'll update the docs to clarify that

File: extensions/harvest/src/listTimeEntries.tsx (hunk 1 above)
Comment (eluce2) [reply extensions/harvest/src/listTimeEntries.tsx]: Yes, good catch. I'll add that

**Review by mathieudutour — APPROVED** [review]
Thanks!
