### PR TITLE
fix js heap error with large results sets by introducting limit pref. fixes #3317.

### LINKED ISSUE #3317: [Recents] ...
# Extension – [Recents](https://github.com/raycast/extensions/tree/f55c8db8d61ec161cefd89d5aed3f9ad56bf1fa4/extensions/recents/)
Author: @GastroGeek

## Description
Recent documents not working, the other commands are e,g. recent apps, folders, etc

## Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

```

## Steps To Reproduce

1. type recent in raycast
2. select recent documents command, press enter

Screenshot 2022-10-25 at 22 29 51

## The current behavior
As image above

## The expected behavior
Assuming it shows a list of recent documents
### Raycast version
Version: 1.41.1

### PR DESCRIPTION
**Pull request by GastroGeek**
## Description

Bug fix for https://github.com/raycast/extensions/issues/3317 by way of user configurable preference/limit.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

File: extensions/recents/src/recents.tsx [hunk 1]
```diff
@@ -49,6 +54,7 @@ const getRecents = async (scope: string | undefined, callback: (result: Spotligh
       query: queryParts.query,
       directories: queryParts.directories,
       attributes: ["kMDItemDisplayName", "kMDItemKind", "kMDItemLastUsedDate"],
+      limit,
```
Comment (pernielsentikaer) [inline extensions/recents/src/recents.tsx:57]:
```suggestion
      limit || 1000,
```
If you delete the preference value it's blank and might cause the heap size error again 😊

Comment (GastroGeek) [reply extensions/recents/src/recents.tsx]: done! good spot!
